<html>
<head>
<title>Freelance Foreign Correspondent</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<h1>Freelance Foreign Correspondent</h1>
<p>
A lot of people ask how to make it as a freelance foreign correspondent. They've often heard, or are telling their own, horror stories of making no money, lack of safety, etc. I tell them it's possible to make great money, have the most amazing adventures and do genuinely worthwhile reporting; but there are also issues, both personal and professional. The industry is broadly a farce but you can use that to your advantage. Like all advice, this is very personal and worked for me and may not work for you. That's because we're different people who have different ambitions, think differently and so engage with the world differently. So take whatever elements you think could work for you and discard the rest. It's also done looking back rather than forward. I didn't plan with these things in mind; it's just stuff that worked out and I can see why now. I wouldn't have liked much of this advice back in 2010, wouldn't have understood it and wouldn't have followed it!
<br><br>
These are some very quick notes from chats with freelancers over the years which I want to expand on and formalize at some point. Part of the reason I'm making this public is because I want the people that succeed to not be the career-climbing rich kids who have the right friends in New York and London but the ones who are from obscure backgrounds, happiest working in the trenches and so genuinely reporting on the places they're in; that will ultimately make journalism better. — <a href="https://www.girishgupta.com">Girish Gupta</a>, May 6, 2020
<br><br>
Go to a place  with few freelancers and an amazing story. They do exist. (I was lucky with where I ended up.)
<br><br>
A lot of freelancers don't seem to understand that they need to make real money, not just enough to get by in the place they're in. Having real money come in will allow them to keep going, do the stories they really want to do and to keep themselves safe. Work out how to run a sustainable business and use that money to buy equipment, resources and, ultimately, time. This will allow you to take risks, go to a place with no commission but the knowledge that you're going to be okay. (I worked in Venezuela for five years as a freelancer, made $10k a month towards the end of it and, thanks to that, was able to do whatever stories I wanted to with all the insurance, training, equipment and anything else I could possibly want; I know it's uncouth to talk about money but that's a major fallacy as it's absolutely key to being a freelancer.)
<br><br>
Pitch everything, every day: things that would be a dream and things you don't necessarily want to do; make the economics work (i.e., do stuff that's quick and easy to allow you the resources to stuff that you really want to do); do multiple versions of the same story across text/radio/video/pics as well; even if you don't have a commission, record at least the audio of every interview if possible and take photos as you never know when they may sell; be systematic in knowing who your possible clients are and who those are that you've worked with; be systematic in what you earn every month, what you spend, where it comes from; double-up on expenses, i.e., charge everyone as much as you can for everything; always up prices when you can; build relationships with editors you care for and offer work you want to do (I was extremely lucky in being able to base myself, even for my freelance work, in the Caracas Reuters bureau, with an amazing team from whom I learned so much and eventually joined formally; align with serious journalists and news outlets like Reuters who are actually on the ground); mention where you are and what you're up to on Twitter, etc.; be militant with payments (I fined on day 30 and took to court on day 60; it worked extremely well and everyone I fined or took to court asked for follow-up work); get to know other reporters here and cover for them when they're away; build up a nice list of "people I've worked for" so you can say, "I worked for..."; most news outlets nowadays aren't very good, don't have resources, etc, but you should use that to your advantage to make money, get your name out there and do bigger and better stuff; have fun and do amazing things!
<br><br>
In terms of safety: know first aid properly and have stuff immediately to hand (i.e., don't just carry a red kit at the bottom of your bag but know exactly where the tourniquet, chest seal etc. are, how to get to them in three seconds and what to do with them); tell people where you're going precisely (times, dates, plate numbers, phone numbers); let them track you; buy a satphone if legal where you are (they're really not expensive at all nowadays in terms of equipment or calls); and basic stuff like redundancy, so have backup tourniquets, battery packs, cash, cables, water, water purification, Soylent, nuts, whatever (also digital backups (I like <a href="https://www.arqbackup.com">Arq</a>), both online and physical; think about digital security: have 2FA on (<a href="https://www.globalotp.com">globalotp.com</a> may help!), use something like <a href="https://www.dashlane.com">Dashlane</a> for passwords). Be self-sufficient, independent. Know where hospitals are; be in touch with the smart person at a nearby place who gets stuff done. And as soon as you're uncomfortable about a situation, get out! (The two times I was detained (Egypt and Ven) were both entirely my fault for sticking around just an hour or so too long; I knew it at the time but didn't say anything to colleagues.) Broadly, be prepared for the worst-case scenario, not the hopeful-case scenario. "Worst case is that I get kidnapped here but that won't happen so I won't prepare for it," is too often a line of thought; why not just prepare for it and then be more confident and happier?
<br><br>
- <a href="https://paydesk.co">Paydesk</a><br>
- <a href="https://www.thestorymarket.co">Story Market</a><br>
- <a href="https://www.frontlinefreelance.org">FFR</a><br>
- <a href="https://rorypecktrust.org">Rory Peck</a><br>
</p>
</body>
</html>